server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_routh #路由的ID没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
            #- After=2021-12-06T17:29:15.228+08:00[Asia/Shanghai]
            #- Cookie=username,song
            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式

        - id: payment_routh2 #payment_routh #路由的ID没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

