#8004表示注册到zookeeper服务器的支付服务提供者的端口号
server:
  port: 8004

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 10.23.63.89:2181